export const munchieBox = {
  number: 1,
  title: "Munchie Box",
  price: 20.5,
  description:
    "Prawn Toast (4) / Spare Ribs (4) / Chicken Balls (4) Mini Spring Rolls (4) Chicken Wings (4) / Egg Fried Rice (1) / Chips / Sauce (2) Can of Juice (2)",
};

export const chefsCombo = {
  number: 2,
  title: "Chef's Combo",
  price: 13.5,
  description:
    "(BBQ Ribs, Pancake Roll, Sesame Prawn Toast, Satay Chicken Skewers & Crispy Won Ton)",
};

export const crispyAromaticDuck = {
  number: 3,
  title: "Crispy Aromatic Duck",
  listItem1: {
    size: `¼`,
    price: 13,
  },
  listItem2: {
    size: "½",
    price: 23,
  },
  listItem3: {
    size: "Whole",
    price: 40,
  },
};

export const startersArr = [
  {
    number: 4,
    name: "Satay Chicken Skewers",
    quantity: 4,
    price: 6.5,
    description: null,
    icon: "🥜",
  },
  {
    number: 5,
    name: "Sesame Prawn Toast",
    quantity: 8,
    price: 6.2,
    description: null,
    icon: null,
  },
  {
    number: 6,
    name: "Crispy Pancake Rolls",
    quantity: 4,
    price: 5.2,
    description: null,
    icon: null,
  },
  {
    number: 7,
    name: "Mini Vegetable Pancake Rolls",
    quantity: 10,
    price: 4.5,
    description: null,
    icon: null,
  },
  {
    number: 8,
    name: "Chicken & Cheese Pancake Rolls",
    quantity: 4,
    price: 5.2,
    description: null,
    icon: null,
  },
  {
    number: 9,
    name: "Crispy Won Ton",
    quantity: 8,
    price: 5.2,
    description: null,
    icon: null,
  },
  {
    number: 10,
    name: "Crispy Seaweed",
    quantity: null,
    price: 6,
    description: null,
    icon: null,
  },
  {
    number: 11,
    name: "Peking Spare Ribs",
    quantity: null,
    price: 7,
    description: null,
    icon: null,
  },
  {
    number: 12,
    name: "Barbecue Spare Ribs",
    quantity: null,
    price: 7,
    description: null,
    icon: null,
  },
  {
    number: 13,
    name: "Sweet & Sour Spare Ribs",
    quantity: null,
    price: 7,
    description: null,
    icon: null,
  },
  {
    number: 14,
    name: "Kung Po Spare Ribs",
    quantity: null,
    price: 7,
    description: null,
    icon: "🌶️",
  },
  {
    number: 15,
    name: "Honey Spare Ribs",
    quantity: null,
    price: 7,
    description: null,
    icon: null,
  },
  {
    number: 16,
    name: "Salt & Pepper Chicken Wings",
    quantity: null,
    price: 6.8,
    description: null,
    icon: "🌶️",
  },
  {
    number: 17,
    name: "Smoked Corn Chicken",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 18,
    name: "Prawn Crackers",
    quantity: null,
    price: 3.0,
    description: null,
    icon: null,
  },
];

export const dimSumArr = [
  {
    number: 19,
    name: "Sia Mai (Steamed Pork Dumplings)",
    price: 5.5,
    description: null,
    icon: null,
  },
  {
    number: 20,
    name: "Har Gow (Steamed Shrimp Dumplings)",
    price: 5.5,
    description: null,
    icon: null,
  },
  {
    number: 21,
    name: "Jiao Zi (Pan Fried Pork Dumplings)",
    price: 5.5,
    description: null,
    icon: null,
  },
];

export const saltAndPepperDishesArr = [
  {
    number: 22,
    name: "Salt & Pepper Chicken",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🌶️",
  },
  {
    number: 23,
    name: "Salt & Pepper Chicken Balls",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🌶️",
  },
  {
    number: 24,
    name: "Salt & Pepper Spare Ribs",
    quantity: null,
    price: 7.0,
    description: null,
    icon: "🌶️",
  },
  {
    number: 25,
    name: "Salt & Pepper Chips",
    quantity: null,
    price: 5.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 26,
    name: "Salt & Pepper King Prawns",
    quantity: null,
    price: 8.2,
    description: null,
    icon: "🌶️",
  },
  {
    number: 27,
    name: "Salt & Pepper Chef's Special",
    description:
      "Min. for 2 persons (Chicken, Ribs, Mini Pancake Rolls & Chips)",
    quantity: null,
    price: 13.9,
    icon: "🌶️",
  },
  {
    number: 27,
    name: "Salt & Pepper Tofu",
    quantity: null,
    price: 7.0,
    description: null,
    icon: "🌶️",
  },
];

export const soupsArr = [
  {
    number: 28,
    name: "Chicken & Mushroom Soup",
    quantity: null,
    price: 4.8,
    description: null,
    icon: null,
  },
  {
    number: 29,
    name: "Chicken & Noodle Soup",
    quantity: null,
    price: 4.8,
    description: null,
    icon: null,
  },
  {
    number: 30,
    name: "Chicken & Sweetcorn Soup",
    quantity: null,
    price: 4.8,
    description: null,
    icon: null,
  },
  {
    number: 31,
    name: "Hot & Sour Soup",
    quantity: null,
    price: 5.0,
    description: null,
    icon: "🌶️",
  },
  {
    number: 32,
    name: "Tom Yam Soup",
    quantity: null,
    price: 5.0,
    description: null,
    icon: "🌶️",
  },
];

export const sweetAndSourDishesArr = [
  {
    number: 33,
    name: "Crispy Chicken Balls",
    quantity: 9,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 34,
    name: "Crispy Pork Balls",
    quantity: 9,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 35,
    name: "Crispy Prawn Balls",
    quantity: 9,
    price: 8.2,
    description: null,
    icon: null,
  },
  {
    number: 36,
    name: "Sweet & Sour Chicken Hong Kong Style",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 37,
    name: "Sweet & Sour Pork Hong Kong Style",
    quantity: null,
    price: 7.0,
    description: null,
    icon: null,
  },
  {
    number: 38,
    name: "Sweet & Sour King Prawns Hong Kong Style",
    quantity: null,
    price: 8.2,
    description: null,
    icon: null,
  },
  {
    number: 39,
    name: "Sweet & Sour Special Hong Kong Style",
    quantity: null,
    price: 8.0,
    description: null,
    icon: null,
  },
  {
    number: 40,
    name: "Sweet & Sour Mixed Vegetables",
    quantity: null,
    price: 6.5,
    description: null,
    icon: null,
  },
];

export const curryDishesArr = [
  {
    number: 41,
    name: "Chicken with Curry Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🌶️",
  },
  {
    number: 42,
    name: "Pork with Curry Sauce",
    quantity: null,
    price: 7.0,
    description: null,
    icon: "🌶️",
  },
  {
    number: 43,
    name: "Beef with Curry Sauce",
    quantity: null,
    price: 7.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 44,
    name: "King Prawn with Curry Sauce",
    quantity: null,
    price: 7.8,
    description: null,
    icon: "🌶️",
  },
  {
    number: 45,
    name: "Shrimp with Curry Sauce",
    quantity: null,
    price: 7.8,
    description: null,
    icon: "🌶️",
  },
  {
    number: 46,
    name: "Duck with Curry Sauce",
    quantity: null,
    price: 9.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 47,
    name: "House Special with Curry Sauce",
    quantity: null,
    price: 8.0,
    description: null,
    icon: "🌶️",
  },
  {
    number: 48,
    name: "Mixed Vegetables with Curry Sauce",
    quantity: null,
    price: 6.5,
    description: null,
    icon: "🌶️",
  },
];

export const thaiCurryDishesArr = [
  {
    number: 49,
    name: "Chicken with Red Curry",
    quantity: null,
    price: 7.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 50,
    name: "Chicken with Green Curry",
    quantity: null,
    price: 7.5,
    description: null,
    icon: "🌶️🌶️",
  },
  {
    number: 51,
    name: "Beef with Red Curry",
    quantity: null,
    price: 7.7,
    description: null,
    icon: "🌶️",
  },
  {
    number: 52,
    name: "Beef with Green Curry",
    quantity: null,
    price: 7.7,
    description: null,
    icon: "🌶️🌶️",
  },
  {
    number: 53,
    name: "King Prawn with Red Curry",
    quantity: null,
    price: 8.0,
    description: null,
    icon: "🌶️",
  },
  {
    number: 54,
    name: "King Prawn with Green Curry",
    quantity: null,
    price: 8.0,
    description: null,
    icon: "🌶️🌶️",
  },
  {
    number: 55,
    name: "Duck with Red Curry",
    quantity: null,
    price: 10.0,
    description: null,
    icon: "🌶️",
  },
  {
    number: 56,
    name: "Duck with Green Curry",
    quantity: null,
    price: 10.0,
    description: null,
    icon: "🌶️🌶️",
  },
  {
    number: 57,
    name: "House Special with Red Curry",
    quantity: null,
    price: 10.0,
    description: null,
    icon: "🌶️",
  },
  {
    number: 58,
    name: "House Special with Green Curry",
    quantity: null,
    price: 10.0,
    description: null,
    icon: "🌶️🌶️",
  },
];

export const chickenDishesArr = [
  {
    number: 59,
    name: "Chicken with Black Bean & Chilli",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🌶️",
  },
  {
    number: 60,
    name: "Chicken with Mushrooms",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 61,
    name: "Chicken with Ginger & Spring Onion",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 62,
    name: "Chicken with Black Pepper",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 63,
    name: "Crispy Chicken with Honey Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 64,
    name: "Chicken with Oyster Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 65,
    name: "Chicken with Peking Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 66,
    name: "Chicken with Cashew Nuts in Plum Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🥜",
  },
  {
    number: 67,
    name: "Chicken with Kung Po Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🌶️",
  },
  {
    number: 68,
    name: "Chicken with Mixed Vegetables",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 69,
    name: "Chicken Chop Suey",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 70,
    name: "Crispy Shredded Chilli Chicken",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🌶️",
  },
  {
    number: 71,
    name: "Chicken with Lemon Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 72,
    name: "Chicken Maryland",
    description:
      "(Chicken Breast, Ham, Pancake Roll, Banana Fritter, Pineapple Fritter & Chips)",
    quantity: null,
    price: 10.5,
    icon: null,
  },
  {
    number: 73,
    name: "Chicken with Orange Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 74,
    name: "Chicken with Pineapple",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 75,
    name: "Chicken with Satay Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🌶️🥜",
  },
  {
    number: 76,
    name: "Chicken Szechuan Style",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🌶️🌶️",
  },
  {
    number: 77,
    name: "Chicken with Cashew Nuts",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🥜",
  },
  {
    number: 78,
    name: "Chicken with Plum Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 79,
    name: "Chicken with Tomatoes",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 80,
    name: "Chicken with Sweetcorn",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 81,
    name: "Chicken with Honey Chilli Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🌶️",
  },
  {
    number: 82,
    name: "Chicken with Cashew Nuts & Pineapple",
    quantity: null,
    price: 7.2,
    description: null,
    icon: "🥜",
  },
  {
    number: 83,
    name: "Roast Chicken with Beansprouts (in BBQ Sauce)",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 84,
    name: "Chicken with Garlic Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 85,
    name: "Chicken with Black Pepper in Honey Sauce",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
];

export const porkDishesArr = [
  {
    number: 86,
    name: "Pork with Kung Po Sauce",
    quantity: null,
    price: 7.0,
    description: null,
    icon: "🌶️",
  },
  {
    number: 87,
    name: "Pork with Cashew Nuts in Plum Sauce",
    quantity: null,
    price: 7.0,
    description: null,
    icon: "🥜",
  },
  {
    number: 88,
    name: "Pork with Black Bean & Chilli",
    quantity: null,
    price: 7.0,
    description: null,
    icon: "🌶️",
  },
  {
    number: 89,
    name: "Pork Szechuan Style",
    quantity: null,
    price: 7.0,
    description: null,
    icon: "🌶️🌶️",
  },
];

export const beefDishesArr = [
  {
    number: 90,
    name: "Beef with Black Pepper",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 91,
    name: "Beef with Mushrooms",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 92,
    name: "Beef with Oyster Sauce",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 93,
    name: "Beef with Ginger & Spring Onion",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 94,
    name: "Beef with Beansprouts",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 95,
    name: "Beef with Mixed Vegetables",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 96,
    name: "Beef Chop Suey",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 97,
    name: "Beef with Cashew Nuts in Plum Sauce",
    quantity: null,
    price: 7.5,
    description: null,
    icon: "🥜",
  },
  {
    number: 98,
    name: "Crispy Shredded Chilli Beef",
    quantity: null,
    price: 7.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 99,
    name: "Beef with Tomatoes",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 100,
    name: "Beef Szechuan Style",
    quantity: null,
    price: 7.5,
    description: null,
    icon: "🌶️🌶️",
  },
  {
    number: 101,
    name: "Beef with Satay Sauce",
    quantity: null,
    price: 7.5,
    description: null,
    icon: "🥜🌶️",
  },
  {
    number: 102,
    name: "Beef with Cashew Nuts",
    quantity: null,
    price: 7.5,
    description: null,
    icon: "🥜",
  },
  {
    number: 103,
    name: "Beef with Cashew Nuts & Pineapple",
    quantity: null,
    price: 7.5,
    description: null,
    icon: "🥜",
  },
  {
    number: 104,
    name: "Beef with Black Bean & Chilli",
    quantity: null,
    price: 7.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 105,
    name: "Beef with Peking Sauce",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 106,
    name: "Beef with Garlic Sauce",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
];

export const duckDishesArr = [
  {
    number: 107,
    name: "Roast Duck with Beansprouts (in BBQ Sauce)",
    quantity: null,
    price: 9.5,
    description: null,
    icon: null,
  },
  {
    number: 108,
    name: "Duck with Honey Chilli Sauce",
    quantity: null,
    price: 9.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 109,
    name: "Duck with Orange Sauce",
    quantity: null,
    price: 9.5,
    description: null,
    icon: null,
  },
  {
    number: 110,
    name: "Duck with Cashew Nuts",
    quantity: null,
    price: 9.5,
    description: null,
    icon: "🥜",
  },
  {
    number: 111,
    name: "Duck with Cashew Nuts in Plum Sauce",
    quantity: null,
    price: 9.5,
    description: null,
    icon: "🥜",
  },
  {
    number: 112,
    name: "Duck with Cashew Nuts & Pineapple",
    quantity: null,
    price: 9.5,
    description: null,
    icon: "🥜",
  },
  {
    number: 113,
    name: "Duck with Black Bean & Chilli",
    quantity: null,
    price: 9.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 114,
    name: "Duck Szechuan Style",
    quantity: null,
    price: 9.5,
    description: null,
    icon: "🌶️🌶️",
  },
  {
    number: 115,
    name: "Duck with Lemon Sauce",
    quantity: null,
    price: 9.5,
    description: null,
    icon: null,
  },
  {
    number: 116,
    name: "Duck with Mushrooms",
    quantity: null,
    price: 9.5,
    description: null,
    icon: null,
  },
  {
    number: 117,
    name: "Duck with Mixed Vegetables",
    quantity: null,
    price: 9.5,
    description: null,
    icon: null,
  },
  {
    number: 118,
    name: "Duck with Tomatoes",
    quantity: null,
    price: 9.5,
    description: null,
    icon: null,
  },
  {
    number: 119,
    name: "Duck with Plum Sauce",
    quantity: null,
    price: 9.5,
    description: null,
    icon: null,
  },
  {
    number: 120,
    name: "Duck with Peking Sauce",
    quantity: null,
    price: 9.5,
    description: null,
    icon: null,
  },
  {
    number: 121,
    name: "Duck with Ginger & Spring Onion",
    quantity: null,
    price: 9.5,
    description: null,
    icon: null,
  },
  {
    number: 122,
    name: "Duck with Garlic Sauce",
    quantity: null,
    price: 9.5,
    description: null,
    icon: null,
  },
];

export const kingPrawnDishesArr = [
  {
    number: 123,
    name: "King Prawn with Black Bean & Chilli",
    quantity: null,
    price: 7.8,
    description: null,
    icon: "🌶️",
  },
  {
    number: 124,
    name: "King Prawn Szechuan Style",
    quantity: null,
    price: 7.8,
    description: null,
    icon: "🌶️🌶️",
  },
  {
    number: 125,
    name: "King Prawn with Kung Po Sauce",
    quantity: null,
    price: 7.8,
    description: null,
    icon: "🌶️",
  },
  {
    number: 126,
    name: "King Prawn with Cashew Nuts",
    quantity: null,
    price: 7.8,
    description: null,
    icon: "🥜",
  },
  {
    number: 127,
    name: "King Prawn with Cashew Nuts & Pineapple",
    quantity: null,
    price: 7.8,
    description: null,
    icon: "🥜",
  },
  {
    number: 128,
    name: "King Prawn with Beansprouts",
    quantity: null,
    price: 7.8,
    description: null,
    icon: null,
  },
  {
    number: 129,
    name: "King Prawn with Peking Sauce",
    quantity: null,
    price: 7.8,
    description: null,
    icon: null,
  },
  {
    number: 130,
    name: "King Prawn with Mushrooms",
    quantity: null,
    price: 7.8,
    description: null,
    icon: null,
  },
  {
    number: 131,
    name: "King Prawn with Ginger & Spring Onion",
    quantity: null,
    price: 7.8,
    description: null,
    icon: null,
  },
  {
    number: 132,
    name: "King Prawn with Tomatoes",
    quantity: null,
    price: 7.8,
    description: null,
    icon: null,
  },
  {
    number: 133,
    name: "King Prawn with Garlic Sauce",
    quantity: null,
    price: 7.8,
    description: null,
    icon: null,
  },
  {
    number: 134,
    name: "King Prawn Chop Suey",
    quantity: null,
    price: 7.8,
    description: null,
    icon: null,
  },
  {
    number: 135,
    name: "King Prawn with Mixed Vegetables",
    quantity: null,
    price: 7.8,
    description: null,
    icon: null,
  },
  {
    number: 136,
    name: "King Prawn with Oyster Sauce",
    quantity: null,
    price: 7.8,
    description: null,
    icon: null,
  },
  {
    number: 137,
    name: "King Prawn with Black Pepper",
    quantity: null,
    price: 7.8,
    description: null,
    icon: null,
  },
  {
    number: 138,
    name: "King Prawn with Satay Sauce",
    quantity: null,
    price: 7.8,
    description: null,
    icon: "🥜🌶️",
  },
];

export const eggFooYungDishesArr = [
  {
    number: 139,
    name: "Plain Egg Foo Yung",
    quantity: null,
    price: 6.5,
    description: null,
    icon: null,
  },
  {
    number: 140,
    name: "Chicken Egg Foo Yung",
    quantity: null,
    price: 7.2,
    description: null,
    icon: null,
  },
  {
    number: 141,
    name: "Pork Egg Foo Yung",
    quantity: null,
    price: 7.0,
    description: null,
    icon: null,
  },
  {
    number: 142,
    name: "Beef Egg Foo Yung",
    quantity: null,
    price: 7.5,
    description: null,
    icon: null,
  },
  {
    number: 143,
    name: "King Prawn Egg Foo Yung",
    quantity: null,
    price: 8.0,
    description: null,
    icon: null,
  },
  {
    number: 144,
    name: "Shrimp Egg Foo Yung",
    quantity: null,
    price: 8.0,
    description: null,
    icon: null,
  },
  {
    number: 145,
    name: "Mushrooms Egg Foo Yung",
    quantity: null,
    price: 7.0,
    description: null,
    icon: null,
  },
  {
    number: 146,
    name: "Mixed Vegetables Egg Foo Yung",
    quantity: null,
    price: 7.0,
    description: null,
    icon: null,
  },
  {
    number: 147,
    name: "Special Egg Foo Yung",
    quantity: null,
    price: 8.0,
    description: null,
    icon: null,
  },
];

export const riceDishesArr = [
  {
    number: 148,
    name: "Egg Fried Rice",
    quantity: null,
    price: 3.5,
    description: null,
    icon: null,
  },
  {
    number: 149,
    name: "Boiled Rice",
    quantity: null,
    price: 3.2,
    description: null,
    icon: null,
  },
  {
    number: 150,
    name: "Yang Chow Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 151,
    name: "Chicken & Ham Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 152,
    name: "Chicken Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 153,
    name: "Beef Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 154,
    name: "Shrimp Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 155,
    name: "King Prawn Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 156,
    name: "Ham Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 157,
    name: "Roast Pork Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 158,
    name: "House Special Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 159,
    name: "Chicken & Prawn Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 160,
    name: "Beef & Prawn Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 161,
    name: "Chicken, Sweetcorn & Mushroom Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 162,
    name: "Duck Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 163,
    name: "Singapore Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 164,
    name: "Chicken & Prawn Fried Rice with Black Bean Sauce",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 165,
    name: "Beef & Prawn Fried Rice with Black Bean Sauce",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 166,
    name: "Mushrooms Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 167,
    name: "Mixed Vegetables Fried Rice",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
];

export const chowMeinDishesArr = [
  {
    number: 168,
    name: "Chicken Chow Mein (Dry)",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 169,
    name: "Chicken Chow Mein with Sauce",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 170,
    name: "Beef Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 171,
    name: "King Prawn Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 172,
    name: "Shrimp Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 173,
    name: "Singapore Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 174,
    name: "Yang Chow Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 175,
    name: "Roast Pork Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 176,
    name: "Mushrooms Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 177,
    name: "Duck Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 178,
    name: "House Special Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 179,
    name: "Chicken & Prawn Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 180,
    name: "Beansprouts Chow Mein",
    quantity: null,
    price: 6,
    description: null,
    icon: null,
  },
  {
    number: 181,
    name: "Mixed Vegetables Chow Mein",
    quantity: null,
    price: 8.5,
    description: null,
    icon: null,
  },
  {
    number: 181,
    name: "Singapore Rice Vermicelli",
    quantity: null,
    price: 9.0,
    description: null,
    icon: "🌶️",
  },
];

export const vegetableDishesArr = [
  {
    number: 182,
    name: "Stir Fried Mixed Vegetables",
    quantity: null,
    price: 6.5,
    description: null,
    icon: null,
  },
  {
    number: 183,
    name: "Stir Fried Beansprouts",
    quantity: null,
    price: 6.5,
    description: null,
    icon: null,
  },
  {
    number: 184,
    name: "Mixed Vegetables with Oyster Sauce",
    quantity: null,
    price: 6.5,
    description: null,
    icon: null,
  },
  {
    number: 185,
    name: "Mixed Vegetables with Black Bean & Chilli",
    quantity: null,
    price: 6.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 186,
    name: "Mixed Vegetables Szechuan Style",
    quantity: null,
    price: 6.5,
    description: null,
    icon: "🌶️🌶️",
  },
  {
    number: 187,
    name: "Mushrooms with Oyster Sauce",
    quantity: null,
    price: 6.5,
    description: null,
    icon: null,
  },
  {
    number: 188,
    name: "Mushrooms with Black Bean & Chilli",
    quantity: null,
    price: 6.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 188,
    name: "Tofu with Black Bean & Chilli",
    quantity: null,
    price: 6.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 188,
    name: "Tofu Szechuan Style",
    quantity: null,
    price: 6.5,
    description: null,
    icon: "🌶️🌶️",
  },
  {
    number: 188,
    name: "Tofu with Mixed Vegetables",
    quantity: null,
    price: 6.5,
    description: null,
    icon: null,
  },
];

export const sideDishesArr = [
  {
    number: 189,
    name: "Chips",
    quantity: null,
    price: 3.5,
    description: null,
    icon: null,
  },
  {
    number: 190,
    name: "Onion Rings",
    quantity: null,
    price: 5.5,
    description: null,
    icon: null,
  },
  {
    number: 191,
    name: "Egg Fried Rice with any Sauce",
    quantity: null,
    price: 5.0,
    description: null,
    icon: null,
  },
  {
    number: 192,
    name: "Chips with any Sauce",
    quantity: null,
    price: 5.0,
    description: null,
    icon: null,
  },
  {
    number: 193,
    name: "Rice & Chips with any Sauce",
    quantity: null,
    price: 7.0,
    description: null,
    icon: null,
  },
  {
    number: 194,
    name: "Chips with Cheese",
    quantity: null,
    price: 5.5,
    description: null,
    icon: null,
  },
  {
    number: 195,
    name: "Chips & Sausage with any Sauce",
    quantity: null,
    price: 6.5,
    description: null,
    icon: null,
  },
];

export const dessertsArr = [
  {
    number: 196,
    name: "Banana Fritters",
    quantity: null,
    price: 5.0,
    description: null,
    icon: null,
  },
  {
    number: 197,
    name: "Pineapple Fritters",
    quantity: null,
    price: 5.0,
    description: null,
    icon: null,
  },
  {
    number: 198,
    name: "Mixed Fritters",
    quantity: null,
    price: 5.0,
    description: null,
    icon: null,
  },
];

export const saucesArr = [
  {
    number: 199,
    name: "Curry Sauce",
    quantity: null,
    price: 3.2,
    description: null,
    icon: "🌶️",
  },
  {
    number: 200,
    name: "Sweet & Sour Sauce",
    quantity: null,
    price: 3.2,
    description: null,
    icon: null,
  },
  {
    number: 201,
    name: "Barbecue Sauce",
    quantity: null,
    price: 3.2,
    description: null,
    icon: null,
  },
  {
    number: 202,
    name: "Kung Po Sauce",
    quantity: null,
    price: 3.5,
    description: null,
    icon: "🌶️",
  },
  {
    number: 203,
    name: "Peking Sauce",
    quantity: null,
    price: 3.5,
    description: null,
    icon: null,
  },
  {
    number: 204,
    name: "Satay Sauce",
    quantity: null,
    price: 3.5,
    description: null,
    icon: "🥜🌶️",
  },
  {
    number: 205,
    name: "Gravy Sauce",
    quantity: null,
    price: 3.2,
    description: null,
    icon: null,
  },
  {
    number: 206,
    name: "Honey Chilli Sauce",
    quantity: null,
    price: 3.5,
    description: null,
    icon: "🌶️",
  },
];

export const mealDeal = {
  mealAPrice: 40,
  mealAItems: [
    "Sweet & Sour Chicken Hong Kong Style",
    "Beef with Black Bean Sauce",
    "Chicken Curry",
    "Egg Fried Rice (2)",
    "Prawn Crackers",
    "Fortune Cookies",
  ],
  mealBPrice: 48,
  mealBItems: [
    "Crispy Pancake Roll",
    "Barbecue Spare Ribs",
    "Chicken with Honey Chilli Sauce",
    "Special Curry",
    "Sweet & Sour King Prawn Cantonese Style",
    "Yang Chow Fried Rice",
    "Banana Fritter",
    "Prawn Crackers",
    "Fortune Cookies",
  ],
};
